# ruff.toml

# Set max line length to 120 characters
line-length = 120

[lint]
# Enable specific linting rule sets
select = ["E", "F", "W", "I"]

# Optionally, ignore specific rules
ignore = ["E501"]  # E501 is "line too long" — if you prefer disabling Ruff's own check for it

# Optionally, extend excludes for folders you don't want to lint
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  "tests/test_handlers_backup.py"
]

# Format the code automatically (like Black)
[format]
quote-style = "double"
line-ending = "lf"