name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python setup.py sdist bdist_wheel

    - name: Install dependencies
      run: |
        pip install dist/*.tar.gz

    - name: Install test dependencies
      run: |
        pip install asynctest tornado pytest

    - name: Run tests
      run: |
        pytest tests/test_handlers.py
